// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_vjm12.Models;

namespace Mission06_vjm12.Migrations
{
    [DbContext(typeof(NewMovieContext))]
    [Migration("20230214045321_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_vjm12.Models.NewMovie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Romance/Adventure",
                            Director = "Rob Reiner",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "The Princess Bride",
                            Notes = "",
                            Rating = "PG",
                            Year = 1987
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Comedy/Romance",
                            Director = "Blake Edwards",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "The Great Race",
                            Notes = "",
                            Rating = "PG",
                            Year = 1965
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Family/Adventure",
                            Director = "Dean DeBlois, Chris Sanders",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "How To Train Your Dragon",
                            Notes = "",
                            Rating = "PG",
                            Year = 2010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
