// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_vjm12.Models;

namespace Mission06_vjm12.Migrations
{
    [DbContext(typeof(NewMovieContext))]
    [Migration("20230221233826_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_vjm12.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Animation"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            CategoryID = 12,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryID = 13,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryID = 14,
                            CategoryName = "Western"
                        });
                });

            modelBuilder.Entity("Mission06_vjm12.Models.NewMovie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 2,
                            Director = "Rob Reiner",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "The Princess Bride",
                            Notes = "",
                            Rating = "PG",
                            Year = 1987
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 2,
                            Director = "Blake Edwards",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "The Great Race",
                            Notes = "",
                            Rating = "PG",
                            Year = 1965
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 3,
                            Director = "Dean DeBlois, Chris Sanders",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "How To Train Your Dragon",
                            Notes = "",
                            Rating = "PG",
                            Year = 2010
                        });
                });

            modelBuilder.Entity("Mission06_vjm12.Models.NewMovie", b =>
                {
                    b.HasOne("Mission06_vjm12.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
